# Generated by Django 4.2.7 on 2023-12-05 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('invoice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('passport_number', models.CharField(max_length=255)),
                ('applied_country', models.CharField(max_length=255)),
                ('file', models.CharField(max_length=10000)),
                ('contact', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('REFUNDED', 'Refunded'), ('PROCESSING_CANCELLED', 'Processing_Cancelled'), ('VISA_REJECTED', 'Visa_Rejected'), ('VISA_SUCCESS', 'Visa_Success'), ('PASSPORT_SUBMITED_ON_EMBASSY', 'Passport_Submited_On_Embassy'), ('PERMIT_RECEIVED', 'Permit_Received'), ('SUBMISSION_RECEIVED', 'Submission_Received'), ('APPLIED', 'Applied')], default='APPLIED', max_length=50)),
                ('remark', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch')),
                ('customer_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
            ],
        ),
    ]
