# Generated by Django 4.2.7 on 2024-01-01 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_branch_city'),
        ('customer', '0004_alter_customer_customer_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='branch.branch'),
        ),
    ]
