# Generated by Django 4.2.7 on 2024-01-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customer_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='file',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
