# Generated by Django 4.2.7 on 2023-12-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_bank_name_alter_payment_cheque_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
