# Generated by Django 4.2.7 on 2023-11-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_name_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_at',
            new_name='date_joined',
        ),
    ]
