# Generated by Django 4.2.7 on 2023-11-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_created_at_user_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_joined',
            new_name='created_at',
        ),
    ]
