# Generated by Django 4.2.7 on 2023-12-19 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_branch_city'),
        ('user', '0010_remove_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='branch.branch'),
            preserve_default=False,
        ),
    ]
