# Generated by Django 4.2.7 on 2023-12-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_log', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_log',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
